
package Frame;


public class MainFrame extends javax.swing.JFrame {

    
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Judullbl = new javax.swing.JLabel();
        SubJudullbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pendaftaranbtn = new javax.swing.JButton();
        ortubtn = new javax.swing.JButton();
        bayarbtn = new javax.swing.JButton();
        jurusanbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        footerisilbl = new javax.swing.JLabel();
        SMANlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(190, 190, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        Judullbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Judullbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Judullbl.setText("PENERIMAAN PESERTA DIDIK BARU SMAN 1 SUNGAI LOBAN");
        Judullbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Judullbl.setIconTextGap(5);

        SubJudullbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubJudullbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SubJudullbl.setText("Tahun Ajaran 2024");
        SubJudullbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SubJudullbl.setIconTextGap(5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubJudullbl, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Judullbl, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judullbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubJudullbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        pendaftaranbtn.setBackground(new java.awt.Color(153, 153, 153));
        pendaftaranbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendaftaranbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard_notes_list_tasks_icon_191193.png"))); // NOI18N
        pendaftaranbtn.setText("PENDAFTARAN");
        pendaftaranbtn.setBorderPainted(false);
        pendaftaranbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendaftaranbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pendaftaranbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pendaftaranbtn.setIconTextGap(10);
        pendaftaranbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendaftaranbtnActionPerformed(evt);
            }
        });

        ortubtn.setBackground(new java.awt.Color(153, 153, 153));
        ortubtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ortubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/3289576-individual-man-people-person_107097.png"))); // NOI18N
        ortubtn.setText("BIODATA ORANG TUA");
        ortubtn.setBorderPainted(false);
        ortubtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ortubtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ortubtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ortubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortubtnActionPerformed(evt);
            }
        });

        bayarbtn.setBackground(new java.awt.Color(153, 153, 153));
        bayarbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bayarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carduse_card_payment_5122.png"))); // NOI18N
        bayarbtn.setText("PEMBAYARAN");
        bayarbtn.setBorderPainted(false);
        bayarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bayarbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bayarbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bayarbtn.setIconTextGap(10);
        bayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarbtnActionPerformed(evt);
            }
        });

        jurusanbtn.setBackground(new java.awt.Color(153, 153, 153));
        jurusanbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jurusanbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/school_icon_234810.png"))); // NOI18N
        jurusanbtn.setText("JURUSAN");
        jurusanbtn.setBorderPainted(false);
        jurusanbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jurusanbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jurusanbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jurusanbtn.setIconTextGap(10);
        jurusanbtn.setRolloverEnabled(false);
        jurusanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ortubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pendaftaranbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addComponent(jurusanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendaftaranbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ortubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(bayarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jurusanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, 600));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        footerisilbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        footerisilbl.setText("Mari kita majukan bangsa Indonesia, melalui Teknologi Informasi yang tepat yang tepat guna pada dunia pendidikan Indonesia.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(footerisilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(footerisilbl)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 800, 50));

        SMANlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/30303638.150203120419.png"))); // NOI18N
        jPanel1.add(SMANlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarbtnActionPerformed
        PembayaranFrame bf = new PembayaranFrame();
        bf.setVisible(true);
        dispose();
    }//GEN-LAST:event_bayarbtnActionPerformed

    private void pendaftaranbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendaftaranbtnActionPerformed
        PendaftaranFrame pf = new PendaftaranFrame();
        pf.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_pendaftaranbtnActionPerformed

    private void ortubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortubtnActionPerformed
        OrangTuaFrame of = new OrangTuaFrame();
        of.setVisible(true);
        dispose();
    }//GEN-LAST:event_ortubtnActionPerformed

    private void jurusanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanbtnActionPerformed
        NilaiFrame nf = new NilaiFrame();
        nf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jurusanbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judullbl;
    private javax.swing.JLabel SMANlbl;
    private javax.swing.JLabel SubJudullbl;
    private javax.swing.JButton bayarbtn;
    private javax.swing.JLabel footerisilbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jurusanbtn;
    private javax.swing.JButton ortubtn;
    private javax.swing.JButton pendaftaranbtn;
    // End of variables declaration//GEN-END:variables
}
