
package Frame;

import db.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Nilai;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


public class NilaiFrame extends javax.swing.JFrame {

    Nilai nilai;
    private final int SEDANG_TAMBAH= 001;
    private final int SEDANG_UBAH = 002;

    private int status;
    
    public NilaiFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        status = SEDANG_TAMBAH;
        RefreshData();
    }

        public ArrayList<Nilai> getNilaiList () {
        ArrayList<Nilai> nilaiList = new ArrayList<Nilai>();
        Koneksi koneksi = new Koneksi();
        Connection connection = koneksi.getConnection();
        
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT nilai.*, pendaftaran.nama_siswa FROM nilai INNER JOIN pendaftaran ON nilai.no_daftar = pendaftaran.no_daftar";
        String order = " ORDER BY nilai.no_nilai";
        
        query = query+order;
        try{
            ps = connection.prepareStatement(query);

            rs = ps.executeQuery();
            while(rs.next()){
                nilai = new Nilai(
                        rs.getString("nilai.no_nilai"),
                        rs.getString("no_daftar"),
                        rs.getString("nilai"),
                        rs.getString("jurusan"),
                        rs.getString("pendaftaran.nama_siswa"));
                nilaiList.add(nilai);
            }
        } catch(SQLException ex){
            System.err.println("ERROR getNilaiList: "+ex);
            System.err.println(ex.getMessage());
        }
        return nilaiList;
    }
    
        public void selectNilai(){
        ArrayList<Nilai> list;
        list = getNilaiList();
        DefaultTableModel model = (DefaultTableModel)JurusanTable.getModel();
        Object[] row =  new Object[5];
        
        for (int i=0; i<list.size(); i++){
            row[0] = list.get(i).getNoNilai();
            row[1] = list.get(i).getNoDaftar();
            row[2] = list.get(i).getNamaSiswa();
            row[3] = list.get(i).getNilai();
            row[4] = list.get(i).getJurusan();           
            model.addRow(row);
        }
    }
      
    public final void RefreshData(){
        DefaultTableModel  dtmbk = (DefaultTableModel) JurusanTable.getModel();
        dtmbk.setRowCount(0);
        selectNilai();
    }
    
    
        public final void resetForm(){
        nodaftartf.setText("");
        siswatf.setText("");
        nilaitf.setText("");
        jurusancbb.setSelectedItem("- Pilih Jurusan -");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nonilaitf = new javax.swing.JTextField();
        KomponenPanel = new javax.swing.JPanel();
        siswalbl = new javax.swing.JLabel();
        siswatf = new javax.swing.JTextField();
        nilailbl = new javax.swing.JLabel();
        nilaitf = new javax.swing.JTextField();
        jurusanlbl = new javax.swing.JLabel();
        jurusancbb = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nodaftartf = new javax.swing.JTextField();
        Caribtn = new javax.swing.JButton();
        nodaftarlbl = new javax.swing.JLabel();
        TabelPanel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        JurusanTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        KomponenPanel.setBackground(new java.awt.Color(190, 190, 190));
        KomponenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PILIH JURUSAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 18))); // NOI18N

        siswalbl.setText("NAMA SISWA");

        nilailbl.setText("NILAI");

        jurusanlbl.setText("JURUSAN");

        jurusancbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jurusan -", "MIPA", "IPS" }));
        jurusancbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusancbbActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(153, 153, 153));
        btnSimpan.setText("Save");
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(153, 153, 153));
        btnUbah.setText("Edit");
        btnUbah.setBorderPainted(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(153, 153, 153));
        btnHapus.setText("Delete");
        btnHapus.setBorderPainted(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 153, 153));
        btnKeluar.setText("Return");
        btnKeluar.setBorderPainted(false);
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnKosong.setBackground(new java.awt.Color(153, 153, 153));
        btnKosong.setText("Clear");
        btnKosong.setBorderPainted(false);
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Print");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nodaftartf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodaftartfActionPerformed(evt);
            }
        });

        Caribtn.setText("Cari");
        Caribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaribtnActionPerformed(evt);
            }
        });

        nodaftarlbl.setText("NO DAFTAR");

        javax.swing.GroupLayout KomponenPanelLayout = new javax.swing.GroupLayout(KomponenPanel);
        KomponenPanel.setLayout(KomponenPanelLayout);
        KomponenPanelLayout.setHorizontalGroup(
            KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KomponenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nodaftarlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siswalbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(nilailbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jurusanlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jurusancbb, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KomponenPanelLayout.createSequentialGroup()
                                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nilaitf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(siswatf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                                        .addComponent(nodaftartf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Caribtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKeluar))))
                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KomponenPanelLayout.setVerticalGroup(
            KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KomponenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodaftartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caribtn)
                    .addComponent(nodaftarlbl)
                    .addComponent(btnKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siswalbl)
                    .addComponent(siswatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaitf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilailbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusancbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jurusanlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnKosong)
                    .addComponent(jButton1)))
        );

        getContentPane().add(KomponenPanel, java.awt.BorderLayout.PAGE_START);

        TabelPanel.setBackground(new java.awt.Color(190, 190, 190));

        JurusanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO NILAI", "NO DAFTAR", "NILAI", "JURUSAN", "NAMA SISWA"
            }
        ));
        JurusanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JurusanTableMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(JurusanTable);

        javax.swing.GroupLayout TabelPanelLayout = new javax.swing.GroupLayout(TabelPanel);
        TabelPanel.setLayout(TabelPanelLayout);
        TabelPanelLayout.setHorizontalGroup(
            TabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabelPanelLayout.setVerticalGroup(
            TabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(TabelPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        Nilai nilai = new Nilai();
        nilai.setNamaSiswa(siswatf.getText());
        nilai.setNilai(nilaitf.getText());
        nilai.setJurusan(jurusancbb.getSelectedItem().toString());
        nilai.setNoNilai(nonilaitf.getText());        
              
        if( siswatf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
        }else{
            
            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
                    String qry = "UPDATE nilai SET nama_siswa = ?, nilai = ?, jurusan = ? WHERE no_nilai = ?";
                    
                        ps = con.prepareStatement(qry);
//                        ps.setInt(0, nilai.getNoNilai());
                        ps.setString(1, nilai.getNamaSiswa());
                        ps.setString(2, nilai.getNilai());
                        ps.setString(3, nilai.getJurusan());
                        ps.setString(4, nilai.getNoNilai());
                        
                                                
                        ps.executeUpdate();
                        RefreshData();
                        resetForm();
                        JOptionPane.showMessageDialog(null, "Data Berhasil diUbah");
             }catch(SQLException e){
                System.err.println("error :"+e);   
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Nilai nilai = new Nilai();
        nilai.setNoDaftar(nodaftartf.getText());
        nilai.setNilai(nilaitf.getText());
        nilai.setJurusan(jurusancbb.getSelectedItem().toString());        
              
        if( nodaftartf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi data");
        }else{
            
            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
                    String qry = "insert into nilai (no_daftar, nilai, jurusan) "
                            + "values (?,?,?)";
                    
                        ps = con.prepareStatement(qry);
                        ps.setString(1, nilai.getNoDaftar());
                        ps.setString(2, nilai.getNilai());
                        ps.setString(3, nilai.getJurusan());
                        
                        ps.executeUpdate();
                        RefreshData();
                        resetForm();
                        JOptionPane.showMessageDialog(null, "Data Berhasil diSimpan");
             }catch(SQLException e){
                System.err.println("error :"+e);   
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void JurusanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JurusanTableMouseClicked
        int i  = JurusanTable.getSelectedRow();
        if(i>=0) {
            TableModel model  = JurusanTable.getModel();
            nodaftartf.setText(model.getValueAt(i, 0).toString());
            nilaitf.setText(model.getValueAt(i, 1).toString());
            jurusancbb.setSelectedItem(model.getValueAt(i, 2).toString());

        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
        }
    }//GEN-LAST:event_JurusanTableMouseClicked

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        resetForm();
    }//GEN-LAST:event_btnKosongActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = JurusanTable.getSelectedRow();
        if(i>=0){
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Yakin mau hapus ?",
                "Konfirmasi hapus",
                JOptionPane.YES_NO_OPTION);
        if(pilihan==0){
                try{
                    TableModel model = JurusanTable.getModel();
                    Koneksi koneksi = new Koneksi();
                    Connection con = koneksi.getConnection();
                    String executeQuery = "delete from nilai where no_nilai =?";
                    PreparedStatement ps = con.prepareStatement(executeQuery);
                    ps.setString(1, nonilaitf.getText());
                    ps.executeUpdate();
                        RefreshData();
                        resetForm();                   
                } catch (SQLException ex){
                    System.err.println(ex);
                }
            }
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        RefreshData();
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void jurusancbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusancbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusancbbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
         Koneksi koneksi = new Koneksi();
         Connection con= koneksi.getConnection(); 
         String path = "src/Laporan/nilai.jasper";
            HashMap<String, Object> parameter = new HashMap();            
            JasperPrint jp = JasperFillManager.fillReport(path, parameter, con);
            JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        } catch(Exception e) {
            System.err.println("error report :"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CaribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaribtnActionPerformed
       String caridaftar = nodaftartf.getText();
       String namasiswa = siswatf.getText();
       Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
        
        try {
            
            String sql1 = "select * from pendaftaran where no_daftar = ?";
            PreparedStatement ps = con.prepareStatement(sql1);
            ps.setString(1, caridaftar);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                String namadaftar = rs.getString("nama_siswa");
                siswatf.setText(namadaftar);
            }
        } catch(SQLException e){
            System.err.println("error"+e);
        }
    }//GEN-LAST:event_CaribtnActionPerformed

    private void nodaftartfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodaftartfActionPerformed
        String namasiswa = siswatf.getText();
       Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
         try {
            String sql2 = "select * from nilai where nama_siswa = ?";
            PreparedStatement ps = con.prepareStatement(sql2);
            ps.setString(1, namasiswa);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                String nodaftar = rs.getString("no_daftar");
                nodaftartf.setText(nodaftar);
            }
        } catch(SQLException e){
            System.err.println("error"+e);
        }
    }//GEN-LAST:event_nodaftartfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caribtn;
    private javax.swing.JTable JurusanTable;
    private javax.swing.JPanel KomponenPanel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JPanel TabelPanel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jurusancbb;
    private javax.swing.JLabel jurusanlbl;
    private javax.swing.JLabel nilailbl;
    private javax.swing.JTextField nilaitf;
    private javax.swing.JLabel nodaftarlbl;
    private javax.swing.JTextField nodaftartf;
    private javax.swing.JTextField nonilaitf;
    private javax.swing.JLabel siswalbl;
    private javax.swing.JTextField siswatf;
    // End of variables declaration//GEN-END:variables
}
