
package Frame;

import db.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.OrangTua;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


public class OrangTuaFrame extends javax.swing.JFrame {

    OrangTua orangtua;
    private final int SEDANG_TAMBAH= 001;
    private final int SEDANG_UBAH = 002;

    private int status;
    
    public OrangTuaFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        status = SEDANG_TAMBAH;
        RefreshData();        
    }
    
    public ArrayList<OrangTua> getOrangTuaList () {
        ArrayList<OrangTua> orangTuaList = new ArrayList<OrangTua>();
        Koneksi koneksi = new Koneksi();
        Connection connection = koneksi.getConnection();
        
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * From orangtua";
        String order = " ORDER BY orangtua.id_ortu";
        
        query = query+order;
        try{
            ps = connection.prepareStatement(query);

            rs = ps.executeQuery();
            while(rs.next()){
                orangtua = new OrangTua(
                        rs.getInt("id_ortu"),
                        rs.getString("nama_siswa"),
                        rs.getString("nama_ayah"),
                        rs.getString("pekerjaan_ayah"),
                        rs.getString("penghasilan_ayah"),
                        rs.getString("nama_ibu"),
                        rs.getString("pekerjaan_ibu"),
                        rs.getString("penghasilan_ibu"));
                orangTuaList.add(orangtua);
            }
        } catch(SQLException ex){
            System.err.println("ERROR getOrangTuaList: "+ex);
            System.err.println(ex.getMessage());
        }
        return orangTuaList;
    }
    
    public void selectOrangTua(){
        ArrayList<OrangTua> list;
        list = getOrangTuaList();
        DefaultTableModel model = (DefaultTableModel)OrangTuaTable.getModel();
        Object[] row =  new Object[8];
        
        for (int i=0; i<list.size(); i++){
            row[0] = list.get(i).getIdOrtu();
            row[1] = list.get(i).getNamaSiswa();
            row[2] = list.get(i).getNamaAyah();
            row[3] = list.get(i).getPekerjaanAyah();
            row[4] = list.get(i).getPenghasilanAyah();
            row[5] = list.get(i).getNamaIbu();
            row[6] = list.get(i).getPekerjaanIbu();
            row[7] = list.get(i).getPenghasilanIbu();           
            model.addRow(row);
        }
    }
      
    public final void RefreshData(){
        DefaultTableModel  dtmbk = (DefaultTableModel) OrangTuaTable.getModel();
        dtmbk.setRowCount(0);
        selectOrangTua();
    }
    
    public final void resetForm(){
        siswatf.setText("");
        ayahtf.setText("");
        kerjaacbb.setSelectedItem("- Pilih Pekerjaan -");
        gajiacbb.setSelectedItem("- Pilih Penghasilan -");
        ibutf.setText("");
        kerjaicbb.setSelectedItem("- Pilih Pekerjaan -");
        gajiicbb.setSelectedItem("- Pilih Penghasilan -");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KomponenPanel = new javax.swing.JPanel();
        siswalbl = new javax.swing.JLabel();
        siswatf = new javax.swing.JTextField();
        ayahlbl = new javax.swing.JLabel();
        ayahtf = new javax.swing.JTextField();
        kerjaalbl = new javax.swing.JLabel();
        kerjaacbb = new javax.swing.JComboBox<>();
        gajialbl = new javax.swing.JLabel();
        gajiacbb = new javax.swing.JComboBox<>();
        ibulbl = new javax.swing.JLabel();
        ibutf = new javax.swing.JTextField();
        kerjailbl = new javax.swing.JLabel();
        kerjaicbb = new javax.swing.JComboBox<>();
        gajiilbl = new javax.swing.JLabel();
        gajiicbb = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TabelPanel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        OrangTuaTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        KomponenPanel.setBackground(new java.awt.Color(190, 190, 190));
        KomponenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biodata Orang Tua", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 18))); // NOI18N

        siswalbl.setText("NAMA SISWA");

        siswatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswatfActionPerformed(evt);
            }
        });

        ayahlbl.setText("NAMA AYAH");

        kerjaalbl.setText("PEKERJAAN AYAH");

        kerjaacbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pekerjaan -", "Buruh", "Karyawan Swasta", "Nelayan", "Pedagang Besar ", "Pedagang Kecil", "Pensiunan", "Petani", "Peternak", "PNS/TNI/Polri", "TKI", "Tidak bekerja", "Tidak dapat diterapkan", "Wiraswasta", "Wirausaha" }));

        gajialbl.setText("GAJI AYAH");

        gajiacbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Penghasilan -", "Kurang dari 500,000", "500.000 - 999.9999", "1 juta - 1.999.999", "2 juta - 4.999.999", "5 juta - 20 juta", "lebih dari 20 juta", "Tidak Berpenghasilan" }));
        gajiacbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiacbbActionPerformed(evt);
            }
        });

        ibulbl.setText("NAMA IBU");

        ibutf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibutfActionPerformed(evt);
            }
        });

        kerjailbl.setText("PEKERJAAN IBU");

        kerjaicbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pekerjaan -", "Buruh", "Karyawan Swasta", "Nelayan", "Pedagang Besar ", "Pedagang Kecil", "Pensiunan", "Petani", "Peternak", "PNS/TNI/Polri", "TKI", "Tidak bekerja", "Tidak dapat diterapkan", "Wiraswasta", "Wirausaha" }));

        gajiilbl.setText("GAJI IBU");

        gajiicbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Penghasilan -", "Kurang dari 500,000", "500.000 - 999.9999", "1 juta - 1.999.999", "2 juta - 4.999.999", "5 juta - 20 juta;", "lebih dari 20 juta", "Tidak Berpenghasilan" }));

        btnSimpan.setBackground(new java.awt.Color(153, 153, 153));
        btnSimpan.setText("Save");
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(153, 153, 153));
        btnUbah.setText("Edit");
        btnUbah.setBorderPainted(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(153, 153, 153));
        btnHapus.setText("Delete");
        btnHapus.setBorderPainted(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKosong.setBackground(new java.awt.Color(153, 153, 153));
        btnKosong.setText("Clear");
        btnKosong.setBorderPainted(false);
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 153, 153));
        btnKeluar.setText("Return");
        btnKeluar.setBorderPainted(false);
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Print");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KomponenPanelLayout = new javax.swing.GroupLayout(KomponenPanel);
        KomponenPanel.setLayout(KomponenPanelLayout);
        KomponenPanelLayout.setHorizontalGroup(
            KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KomponenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ayahlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(siswalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kerjaalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                        .addComponent(gajialbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kerjaacbb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayahtf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siswatf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajiacbb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kerjailbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibulbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajiilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kerjaicbb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibutf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajiicbb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(btnKosong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );
        KomponenPanelLayout.setVerticalGroup(
            KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KomponenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siswatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibulbl)
                            .addComponent(ibutf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ayahtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayahlbl)
                            .addComponent(kerjailbl)
                            .addComponent(kerjaicbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kerjaacbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kerjaalbl)
                            .addComponent(gajiilbl)
                            .addComponent(gajiicbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gajiacbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajialbl))
                        .addGap(12, 12, 12))
                    .addGroup(KomponenPanelLayout.createSequentialGroup()
                        .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KomponenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnKeluar)
                                .addComponent(btnSimpan))
                            .addComponent(siswalbl))
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKosong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(KomponenPanel, java.awt.BorderLayout.PAGE_START);

        TabelPanel.setBackground(new java.awt.Color(190, 190, 190));

        OrangTuaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ORANG TUA", "NAMA SISWA", "NAMA AYAH", "PEKERJAAN AYAH", "PENGHASILAN AYAH", "NAMA IBU", "PEKERJAAN IBU", "PENGHASILAN IBU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrangTuaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrangTuaTableMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(OrangTuaTable);

        javax.swing.GroupLayout TabelPanelLayout = new javax.swing.GroupLayout(TabelPanel);
        TabelPanel.setLayout(TabelPanelLayout);
        TabelPanelLayout.setHorizontalGroup(
            TabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabelPanelLayout.setVerticalGroup(
            TabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabelPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(TabelPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        resetForm();
    }//GEN-LAST:event_btnKosongActionPerformed

    private void siswatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siswatfActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        OrangTua orangtua = new OrangTua();
        orangtua.setNamaSiswa(siswatf.getText());
        orangtua.setNamaAyah(ayahtf.getText());
        orangtua.setPekerjaanAyah(kerjaacbb.getSelectedItem().toString());
        orangtua.setPenghasilanAyah(gajiacbb.getSelectedItem().toString());
        orangtua.setNamaIbu(ibutf.getText());
        orangtua.setPekerjaanIbu(kerjaicbb.getSelectedItem().toString());
        orangtua.setPenghasilanIbu(gajiicbb.getSelectedItem().toString());
        
              
        if( siswatf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi data");
        }else{
            
            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
                    String qry = "insert into orangtua " 
                            + "(nama_siswa, nama_ayah, pekerjaan_ayah, penghasilan_ayah, nama_ibu, pekerjaan_ibu, penghasilan_ibu) "
                            + "values (?,?,?,?,?,?,?)";
                    
                        ps = con.prepareStatement(qry);
                        ps.setString(1, orangtua.getNamaSiswa());
                        ps.setString(2, orangtua.getNamaAyah());
                        ps.setString(3, orangtua.getPekerjaanAyah());
                        ps.setString(4,orangtua.getPenghasilanAyah());
                        ps.setString(5, orangtua.getNamaIbu());
                        ps.setString(6, orangtua.getPekerjaanIbu());
                        ps.setString(7,orangtua.getPenghasilanIbu());
                        ps.executeUpdate();
                        RefreshData();
                        resetForm();
             }catch(SQLException e){
                System.err.println("error :"+e);   
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void ibutfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibutfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibutfActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        OrangTua orangtua = new OrangTua();
        orangtua.setNamaSiswa(siswatf.getText());
        orangtua.setNamaAyah(ayahtf.getText());
        orangtua.setPekerjaanAyah(kerjaacbb.getSelectedItem().toString());
        orangtua.setPenghasilanAyah(gajiacbb.getSelectedItem().toString());
        orangtua.setNamaIbu(ibutf.getText());
        orangtua.setPekerjaanIbu(kerjaicbb.getSelectedItem().toString());
        orangtua.setPenghasilanIbu(gajiicbb.getSelectedItem().toString());
        
              
        if( siswatf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
        }else{
            
            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
                    String qry = "update orangtua set "
                            + "nama_siswa=?, nama_ayah=?, pekerjaan_ayah=?, penghasilan_ayah=?, "
                            + "nama_ibu=?, pekerjaan_ibu=?, penghasilan_ibu=? where id_ortu=?";                    
                        ps = con.prepareStatement(qry);
                                                
                        ps.setString(1, orangtua.getNamaSiswa());
                        ps.setString(2, orangtua.getNamaAyah());
                        ps.setString(3, orangtua.getPekerjaanAyah());
                        ps.setString(4,orangtua.getPenghasilanAyah());
                        ps.setString(5, orangtua.getNamaIbu());
                        ps.setString(6, orangtua.getPekerjaanIbu());
                        ps.setString(7,orangtua.getPenghasilanIbu());
                        ps.setInt(8, orangtua.getIdOrtu());
                        ps.executeUpdate();
                        RefreshData();
                        resetForm();
             }catch(SQLException e){
                System.err.println("error :"+e);   
            }
        }        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void OrangTuaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrangTuaTableMouseClicked
        int i  = OrangTuaTable.getSelectedRow();
        if(i>=0) {
            TableModel model  = OrangTuaTable.getModel();

            siswatf.setText(model.getValueAt(i, 1).toString());
            ayahtf.setText(model.getValueAt(i, 2).toString());
            kerjaacbb.setSelectedItem(model.getValueAt(i, 3).toString());
            gajiacbb.setSelectedItem(model.getValueAt(i, 4).toString());
            ibutf.setText(model.getValueAt(i, 5).toString());
            kerjaicbb.setSelectedItem(model.getValueAt(i, 6).toString());
            gajiicbb.setSelectedItem(model.getValueAt(i, 7).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
        }
    }//GEN-LAST:event_OrangTuaTableMouseClicked

    private void gajiacbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiacbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajiacbbActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = OrangTuaTable.getSelectedRow();
        if(i>=0){
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Yakin mau hapus ?",
                "Konfirmasi hapus",
                JOptionPane.YES_NO_OPTION);
        if(pilihan==0){
                try{
                    TableModel model = OrangTuaTable.getModel();
                    Koneksi koneksi = new Koneksi();
                    Connection con = koneksi.getConnection();
                    String executeQuery = "delete from orangtua where nama_siswa =?";
                    PreparedStatement ps = con.prepareStatement(executeQuery);
                    ps.setString(1, siswatf.getText());
                    ps.executeUpdate();
                        RefreshData();
                        resetForm();                   
                } catch (SQLException ex){
                    System.err.println(ex);
                }
            }
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        RefreshData();
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
         Koneksi koneksi = new Koneksi();
         Connection con= koneksi.getConnection(); 
         String path = "src/Laporan/ortu.jasper";
            HashMap<String, Object> parameter = new HashMap();            
            JasperPrint jp = JasperFillManager.fillReport(path, parameter, con);
            JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        } catch(Exception e) {
            System.err.println("error report :"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrangTuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrangTuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrangTuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrangTuaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrangTuaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KomponenPanel;
    private javax.swing.JTable OrangTuaTable;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JPanel TabelPanel;
    private javax.swing.JLabel ayahlbl;
    private javax.swing.JTextField ayahtf;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKosong;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> gajiacbb;
    private javax.swing.JLabel gajialbl;
    private javax.swing.JComboBox<String> gajiicbb;
    private javax.swing.JLabel gajiilbl;
    private javax.swing.JLabel ibulbl;
    private javax.swing.JTextField ibutf;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> kerjaacbb;
    private javax.swing.JLabel kerjaalbl;
    private javax.swing.JComboBox<String> kerjaicbb;
    private javax.swing.JLabel kerjailbl;
    private javax.swing.JLabel siswalbl;
    private javax.swing.JTextField siswatf;
    // End of variables declaration//GEN-END:variables
}
